name: recipe_meal_planning_app
description: A Flutter app for recipe and meal planning.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  provider: ^6.0.0
  http: ^0.13.3

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
